power_heat_topic: /referee/power_heat
robot_status_topic: /referee/robot_status
twist_pub_topic: /chassis/cmd_vel_limited
twist_sub_topic: /chassis/cmd_vel
buffer_control_level: 150.0
buffer_min_level: 50.0
