/chassis_lf_pid:
  ros__parameters:
    command_interface: chassis_left_front/effort
    state_interface: chassis_left_front/velocity
    kp: 515.778
    ki: 0.3438
    kd: 0.0
    max_out: 6.0
    max_iout: 0.75

/chassis_lb_pid:
  ros__parameters:
    command_interface: chassis_left_back/effort
    state_interface: chassis_left_back/velocity
    kp: 515.778
    ki: 0.3438
    kd: 0.0
    max_out: 6.0
    max_iout: 0.75

/chassis_rf_pid:
  ros__parameters:
    command_interface: chassis_right_front/effort
    state_interface: chassis_right_front/velocity
    kp: 515.778
    ki: 0.3438
    kd: 0.0
    max_out: 6.0
    max_iout: 0.75

/chassis_rb_pid:
  ros__parameters:
    command_interface: chassis_right_back/effort
    state_interface: chassis_right_back/velocity
    kp: 515.778
    ki: 0.3438
    kd: 0.0
    max_out: 6.0
    max_iout: 0.75
