offline_broadcaster:
  ros__parameters:
    controller_type: gary_controller/OfflineBroadcaster
    interface_name: offline
    diagnose_topic: /diagnostics
    pub_rate: 10.0

joint_state_broadcaster:
  ros__parameters:
    controller_type: joint_state_broadcaster/JointStateBroadcaster
