hardware_monitor:
  ros__parameters:
    controller_type: gary_controller/HardwareMonitor
    offline_interface_name: offline
    temperature_interface_name: temperature
    overheat_threshold: 80.0
    diagnose_topic: /diagnostics
    pub_rate: 10.0

joint_state_broadcaster:
  ros__parameters:
    controller_type: joint_state_broadcaster/JointStateBroadcaster

calibration_controller:
  ros__parameters:
    controller_type: gary_controller/CalibrationController
    interface_name: reset_position
    motor_names:
      - chassis_left_front
      - chassis_left_back
      - chassis_right_front
      - chassis_right_back
      - rescue_left
      - rescue_right
      - liftup_left
      - liftup_right
      - stretch_left
      - stretch_right
      - sucker_spin
      - ore_rotate
      - gimbal_roll
      - gimbal_pitch
      - gimbal_left
      - gimbal_right
      - image_transmitter_rotate
      - gimbal_yaw