liftup_left_pid:
  ros__parameters:
    controller_type: gary_controller/DualLoopPIDController
    inner_command_interface: liftup_left/effort
    inner_state_interface: liftup_left/velocity
    inner_kp: 0.5
    inner_ki: 0.0
    inner_kd: 0.0
    inner_max_out: 6.0
    inner_max_iout: 3.0
    outer_state_interface: liftup_left/position
    outer_kp: 15.0
    outer_ki: 0.1
    outer_kd: 0.0
    outer_max_out: 10.0
    outer_max_iout: 2.0

liftup_right_pid:
  ros__parameters:
    controller_type: gary_controller/DualLoopPIDController
    inner_command_interface: liftup_right/effort
    inner_state_interface: liftup_right/velocity
    inner_kp: 0.5
    inner_ki: 0.0
    inner_kd: 0.0
    inner_max_out: 6.0
    inner_max_iout: 3.0
    outer_state_interface: liftup_right/position
    outer_kp: 15.0
    outer_ki: 0.1
    outer_kd: 0.0
    outer_max_out: 10.0
    outer_max_iout: 2.0
