rescue_left_pid:
  ros__parameters:
    controller_type: gary_controller/DualLoopPIDController
    inner_command_interface: rescue_left/effort
    inner_state_interface: rescue_left/velocity
    inner_kp: 1.5
    inner_ki: 0.0
    inner_kd: 0.0
    inner_max_out: 0.8
    inner_max_iout: 0.4
    outer_state_interface: rescue_left/position
    outer_kp: 6.0
    outer_ki: 0.0
    outer_kd: 0.0
    outer_max_out: 100.0
    outer_max_iout: 5.0

rescue_right_pid:
  ros__parameters:
    controller_type: gary_controller/DualLoopPIDController
    inner_command_interface: rescue_right/effort
    inner_state_interface: rescue_right/velocity
    inner_kp: 1.5
    inner_ki: 0.0
    inner_kd: 0.0
    inner_max_out: 0.8
    inner_max_iout: 0.4
    outer_state_interface: rescue_right/position
    outer_kp: 6.0
    outer_ki: 0.0
    outer_kd: 0.0
    outer_max_out: 100.0
    outer_max_iout: 5.0