diag_freq: 10.0
diagnose_topic: /diagnostics
node_names:
- /diagnostic_aggregator
- /dr16_receiver
- /rm_referee
- /socket_can_monitor
- /dr16_forwarder
- /shooter_controller
respawn: false
update_rate: 10.0
