diag_freq: 10.0
diagnose_topic: /diagnostics
node_names:
- /diagnostic_aggregator
- /dr16_receiver
- /rm_referee
- /socket_can_monitor
- /mecanum_chassis_solver
- /chassis_teleop
- /chassis_power_control
- /gimbal_teleop
- /gimbal_control
- /dr16_forwarder
- /shooter_controller
- /shooter_heat_control
- /barrel_switcher
- /rm_referee
respawn: false
update_rate: 10.0
